# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exemplo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'exemplo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexemplo.proto\x12\x07\x65xemplo\"\x17\n\x06Numero\x12\r\n\x05valor\x18\x01 \x01(\x05\"\x1d\n\tResultado\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"\x19\n\x08Mensagem\x12\r\n\x05texto\x18\x01 \x01(\t2\xde\x01\n\x0e\x45xemploService\x12.\n\x05\x44obro\x12\x0f.exemplo.Numero\x1a\x12.exemplo.Resultado\"\x00\x12\x32\n\x07Tabuada\x12\x0f.exemplo.Numero\x1a\x12.exemplo.Resultado\"\x00\x30\x01\x12\x30\n\x05Media\x12\x0f.exemplo.Numero\x1a\x12.exemplo.Resultado\"\x00(\x01\x12\x36\n\x08\x43onversa\x12\x11.exemplo.Mensagem\x1a\x11.exemplo.Mensagem\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exemplo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMERO']._serialized_start=26
  _globals['_NUMERO']._serialized_end=49
  _globals['_RESULTADO']._serialized_start=51
  _globals['_RESULTADO']._serialized_end=80
  _globals['_MENSAGEM']._serialized_start=82
  _globals['_MENSAGEM']._serialized_end=107
  _globals['_EXEMPLOSERVICE']._serialized_start=110
  _globals['_EXEMPLOSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
