# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import exemplo_pb2 as exemplo__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in exemplo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExemploServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dobro = channel.unary_unary(
                '/exemplo.ExemploService/Dobro',
                request_serializer=exemplo__pb2.Numero.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.Tabuada = channel.unary_stream(
                '/exemplo.ExemploService/Tabuada',
                request_serializer=exemplo__pb2.Numero.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.Media = channel.stream_unary(
                '/exemplo.ExemploService/Media',
                request_serializer=exemplo__pb2.Numero.SerializeToString,
                response_deserializer=exemplo__pb2.Resultado.FromString,
                _registered_method=True)
        self.Conversa = channel.stream_stream(
                '/exemplo.ExemploService/Conversa',
                request_serializer=exemplo__pb2.Mensagem.SerializeToString,
                response_deserializer=exemplo__pb2.Mensagem.FromString,
                _registered_method=True)


class ExemploServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Dobro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tabuada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Media(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Conversa(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExemploServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dobro': grpc.unary_unary_rpc_method_handler(
                    servicer.Dobro,
                    request_deserializer=exemplo__pb2.Numero.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'Tabuada': grpc.unary_stream_rpc_method_handler(
                    servicer.Tabuada,
                    request_deserializer=exemplo__pb2.Numero.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'Media': grpc.stream_unary_rpc_method_handler(
                    servicer.Media,
                    request_deserializer=exemplo__pb2.Numero.FromString,
                    response_serializer=exemplo__pb2.Resultado.SerializeToString,
            ),
            'Conversa': grpc.stream_stream_rpc_method_handler(
                    servicer.Conversa,
                    request_deserializer=exemplo__pb2.Mensagem.FromString,
                    response_serializer=exemplo__pb2.Mensagem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exemplo.ExemploService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exemplo.ExemploService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExemploService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Dobro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exemplo.ExemploService/Dobro',
            exemplo__pb2.Numero.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tabuada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/exemplo.ExemploService/Tabuada',
            exemplo__pb2.Numero.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Media(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/exemplo.ExemploService/Media',
            exemplo__pb2.Numero.SerializeToString,
            exemplo__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Conversa(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/exemplo.ExemploService/Conversa',
            exemplo__pb2.Mensagem.SerializeToString,
            exemplo__pb2.Mensagem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
