apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: central-monitor
  namespace: chat-system
  labels:
    release: kube-prom
spec:
  selector:
    matchLabels:
      app: central
  namespaceSelector:
    matchNames:
    - chat-system
  endpoints:
  - port: metrics
    path: /metrics
    interval: 10s
