services:
  serverb:
    build: ./serverB
    ports:
      - "3002:3002"
    networks:
      - chat-network

  servera:
    build: ./serverA
    ports:
      - "3001:3001"
    networks:
      - chat-network
    depends_on:
      - serverb

  central:
    build: ./central
    ports:
      - "8080:8080"
    networks:
      - chat-network
    depends_on:
      - servera
      - serverb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - chat-network
    depends_on:
      - central

networks:
  chat-network:
    driver: bridge